apiVersion: apps/v1
kind: Deployment
metadata:
  name: allcountrycode
  labels:
    app: flask-allcountrycode
spec:
  selector:
    matchLabels:
      app: flask-allcountrycode
  replicas: 1
  template:
    metadata:
      labels:
        app: flask-allcountrycode
    spec:
      containers:
      - name: allcountrycode
        image: kumarn50/allcountrycode:v3
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: allcountrycode
  labels:
    app: flask-allcountrycode
spec:
  ports:
  - name: http
    port: 5000
    protocol: TCP
    targetPort: 5000
  selector:
    app: flask-allcountrycode
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: allcountrycode
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  rules:
    - host: sateeshallcountrycodes.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: allcountrycode
                port:
                  number: 5000
